---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1arnxgnua2p7wxy07ezayv9gwrl2ggrwsfj708kcnuqg28j4y9amq0h8uap
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1arnxgnua2p7wxy07ezayv9gwrl2ggrwsfj708kcnuqg28j4y9amq0h8uap
