# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:O2HwszlTDxE84UqQzef1CX0=,iv:QBGSBhhicgczXI4HyCKnq0Nk6o4wAdfM9xZ/jqk4ZVI=,tag:iuMecgFApaf/RF+20ZXXkQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:4yHC4RaDJPOT0cuibugdePqtB66BLe3pRFGVSlD0F4gl5w0ZhQ==,iv:t/vT3SkAjKfJ77dYIv5rGDiNxokzey5FCar1fCYuGgA=,tag:O5QhAErXV24gTPviBexJkA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:/EV185dIG9vyUNhPaEi3Ddvu5g==,iv:WiXlxPw/j6PAa1yfWemDh+HWF6BxPuyDgWv83fpcl7k=,tag:NTenQ8hZEGqGmE9QuHlB8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1arnxgnua2p7wxy07ezayv9gwrl2ggrwsfj708kcnuqg28j4y9amq0h8uap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVFU4THZFNmhGN3A4VEE0
            WUgyYTJRL1JDakpNa1l2ZUpqR0x4dHZIOUJnCmt0Y3ViTEFreXBJdU01TFhpaGlp
            enRCWVJERkVrUUEzV0NWN29zaDhpL0EKLS0tIGJHcVYrcm5YTTFDMHlBMDlBV0Z1
            aHBNY2U1NHozRGFjN0QwUGdHcUUrMkUKyvLbycm34lwampZ1s/idzRT+o+jIKpXy
            tZwUzsQpEsEUCQ3sMHvsNRcx4K2PmIl4MnGmgLw4MNmAd5j8ZGiRgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T21:57:46Z"
    mac: ENC[AES256_GCM,data:NYvg/mWMh2AeheDcm1CD3oy3iTxdP7ImBES32ld6/MwxZ4B2jaPTEY6/72MGNQnuodAKTJSpTL/U9o7/CmGvJgr++0wKKrz5QO3jRluErQV+ZzRO2TnGg78IniAtuqMQo/3iKPuc86JMR6rPN/unlkVjzqpax1TDF4/unfGnXPs=,iv:aWmMeu60ySQwLVjf66jDiFDKxAL1Dl7/oxqmnmEhDJ8=,tag:Kyv2ZolNJtfYcOJxE14lUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
