---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/UTC
  METALLB_LB_RANGE: 10.8.8.242-10.8.8.245
  METALLB_K8S_GATEWAY_ADDR: 10.8.8.243
  METALLB_INGRESS_ADDR: 10.8.8.242
